### ISSUE TITLE
php error undefined property

### ISSUE THREAD

**Issue by joeydaly** [jfox015/Bonfire-News#10]
A PHP ERROR WAS ENCOUNTERED
Severity: Notice

Message: Undefined property: stdClass::$display_name

Filename: content/index.php

Line Number: 15

I installed the module and ran all the migration scripts and went to Content -> News and got the following error

**Comment by jfox015** [comment]
@joeydaly 
Thanks for the note. Are you using the latest and greatest version of Bonfire?

**Comment by joeydaly** [comment]
Using 0.5, what's the best way of upgrading? Actually is there any untold guide for how to setup you're application to make it upgrade safe?

**Comment by jfox015** [comment]
@joeydaly 
I actually looked into this further an identified this as an issue with the [Bonfire core in relation to upgrading to 0.6](https://github.com/ci-bonfire/Bonfire/issues/397). 

The News module's development and sv_merge branches both require 0.6 and the new current_user->display name property hence the error. I'll try and work with @svizion who added that code in the Author_model to think on a temporary fix.

**Comment by og-shawn-crigger** [comment]
Ah the .5 releases,  I believe in .5 we had email and username instead of display name,  But we didn't have a user object on the stock .5 releases.  It is a issue with updating to .6,  the easiest fix would be replace display name with username in the Author model

**Comment by joeydaly** [comment]
I had a few other issues, so I've downloaded the latest release, but I don't think it was .6? anyway I was going to do a clean install and load the module. then try re-write my code so that I can import all the modules correctly. My main issue I think is the theme, I started editing the default theme. Anyway I'll it out on the latest release and see how it goes, cheers.
