### ISSUE TITLE
css_path

### ISSUE THREAD

**Issue by ghost** [jfox015/Bonfire-News#12]
i've installed the module, made the migration.
I got this error when trying to access index.php/admin/content/news

Fatal error: Call to undefined function css_path() in \bonfire\modules\news\controllers\content.php on line 67

**Comment by ghost** [comment]
installed the module on 0.6 dev bonfire, had no problem. seems it comes from the downloaded version. v0.5.2.

**Comment by jfox015** [comment]
@fxguillois Thanks for the follow-up. I will note in the READ ME that 0.6+ is required to use this module.
