### ISSUE TITLE
New article Random Details error

### ISSUE THREAD

**Issue by ghost** [jfox015/Bonfire-News#13]
I'm getting this error in the Random Details section

```
A PHP Error was encountered
Severity: Notice

Message: Undefined variable: article

Filename: content/news_form.php

Line Number: 147

A PHP Error was encountered
Severity: Notice

Message: Trying to get property of non-object

Filename: content/news_form.php

Line Number: 147
```

I've fixed it by making a change on line 146 

`````` else```
to
```elseif(isset($article))```
``````

**Comment by jfox015** [comment]
@seandowney Thanks. This is fixed. I need to think about that block and the use of the Manage permissions here. They're kind of moot because if you don;t have content management permissions you can't see the form.
