### ISSUE TITLE
i got this error on create new news article form. i use relese 0.2 tags.

### ISSUE THREAD

**Issue by phpgeek-programmer** [jfox015/Bonfire-News#17]
i got this error on create new news article form. i use relese 0.2 tags, and bonfire 0.6.1.

![error on create news](https://f.cloud.github.com/assets/3446259/1418060/f4feb5c6-3fa7-11e3-8b0b-69e493e9ca08.png)

I like your news module, and may be will be using it at my production web site. thanks very much

**Comment by phpgeek-programmer** [comment]
I don't understand how to manage category, or edit news content on admin dashboard. I can't find edit button or link on every article. thanks.

**Comment by jfox015** [comment]
@phpgeek-programmer Thanks for the heads up. The 0,2 version in **master** definitely has some known bugs in it. I've addressed a number of these in the 0.3 release in the **development** branch which is actually getting merged and tagged as 0,3 today. So try that one with Bonfire 0.6.1 and let me know if the issue persists.

**Comment by jfox015** [comment]
@phpgeek-programmer You're right, there is no separate category editor...yet. Oops. Shouldn't be too hard to drop in though. You can edit news in the dashboard by clicking the name of the article in the news listing page.

**Comment by phpgeek-programmer** [comment]
hi @jfox015 , i am confuse with your installation tutorial on wiki. on step 2, you say "Extract the contents of the zip into your bonfire install folder". but after installing bonfire at first time, bonfire say to me to remove install direktory, after succesfull installing bonfire. so which directory you mean?

**Comment by jfox015** [comment]
@phpgeek-programmer That should have read "root of your bonfire web site". The news module should not be put in the "install" folder. The wiki has been updated.

**Comment by phpgeek-programmer** [comment]
@jfox015 after trying 0.3 there is no error anymore at create new news. thanks for it. 

but at author field, i cannot find some user to choose as author, even my selves. after new article created, author fields seems to be empty.

**Comment by phpgeek-programmer** [comment]
@jfox015 you say "You're right, there is no separate category editor...yet." would be very nice if it was immediately implemented. :+1:

**Comment by phpgeek-programmer** [comment]
@jfox015 it seems, you forget to change module version to 0.3 at file bonfire/modules/news/config/config.php.

**Comment by jfox015** [comment]
@phpgeek-programmer this is updated is an updated 0.3 tag release.
