### ISSUE TITLE
Missing $table_name Variable

### ISSUE THREAD

**Issue by noxify** [jfox015/Bonfire-News#19]
Hi,

after installing your module i got many sql errors.

i have checked it and the problem is the missing $table_name variable in the model files.

I'm using Bonfire 0.7.

**Comment by jfox015** [comment]
@noxify The News Module 0.3 works with 0.6. I haven't updated it to 0.7 because the file structure changed.

**Comment by noxify** [comment]
Hi,

any plans to update it?

**Comment by jfox015** [comment]
@noxify At this very moment no. I'd have to sweep through and update all my modules. Maybe in the near future though I can make 0.4 versions that are compatible. I'm open to making pull requests for anyone who can make it 0.7 compliant in the meantime.

**Comment by TurtleWolfe** [comment]
I think I'm having the same issue... Have you had any luck with that Noxify?

**Comment by TurtleWolfe** [comment]
I may roll back a site just to .6 just to try your modules... that may even give me enough to reverse engineer them for .7. If I have any success I'll put it back up!

**Comment by jfox015** [comment]
This sounds like an issue specific to running this mod with 0.7 so closing it in favor of a 0.7 update.
