### ISSUE TITLE
News Dates save as 0 on create

### ISSUE THREAD

**Issue by jfox015** [jfox015/Bonfire-News#2]
When creating a new article, dates save as 0 in the DB. They can be fixed on edit.

**Comment by jfox015** [comment]
Fixed by svizion in 0.2

**Comment by ghost** [comment]
Hi jfox,

i've dowloaded your Newsmodule... thnaks for it. But i've got this Bug that if i'm writing a new news article the System didn't save the Date. I use the Bonfire 0.6

**Comment by jfox015** [comment]
The bug should be fixed. Are you using the 0.1 or 0.2 version? 0.1 has the bug. Use the download link on the code page to make sure to grab the latest and greatest.

**Comment by ghost** [comment]
The Updatesystem and the Manifest told me that i am using the 0.2

**Comment by jfox015** [comment]
OK, I've not tested this with the final 0.6 Bonfire release so maybe there's some issue there. We'll have to investigate,

**Comment by ghost** [comment]
If i've got a solution i'll post it here if it's okay for you

**Comment by jfox015** [comment]
Yeah, if you can solve it, def throw me a pull request. Thanks.
