### ISSUE TITLE
Attachment Upload Directory "" is not write-able.

### ISSUE THREAD

**Issue by TurtleWolfe** [jfox015/Bonfire-News#22]
I'm setting both to /public/assets/images/uploads/ but continue to get directory "" not write-able.

**Comment by jfox015** [comment]
@TurtleWolf For _Upload directory path_, enter the full path from the root of your server to up to and including the uploads folder. _Upload directory URL_ should be the web site URL path from the root of your domain (or Bonfire install if it's not installed to the root. Try that and let me know if you keep getting a blank error and we'll debug the values within the content controller.

To keep your images folder clean and tidy and better admin upkeep of the uploads, I do recommend uploading to a separate directory like /public/uploads/.

**Comment by jfox015** [comment]
I think we identified this as a different type of issue so I'm closing this item.
